### ISSUE TITLE
[SUGGESTION] Reduce the size of OCI image

### ISSUE THREAD

**Issue by superdinmc** [Vanilla-OS/Vib#86]
This was once discussed between me and tau in the discord server
He states that
> Every change in an image is layered ontop of the last change. 
> You have to download every layer from the changed one on. 
> 
> This is sadly a limitation of OCI images, though it can probably be improved by downloading it another way.
> 
> So if there is a change in the pico image you will have to download the entire image again.
> If the change is somewhere in nvidia image, then it's only gonns be a few layers.

Once more it have bought attention to me, so I created this issue for friendly future reminder to fix/implement this.

**Comment by axtloss** [comment]
fix or implement what? you don't really state what needs to be changed
the size of the oci image isn't up to us, it's up to the user who defines the recipe to make sure it only includes what is necessary to reduce the image size

**Comment by axtloss** [comment]
tau confirmed that this issue has nothing to do with vib, closing

**Comment by taukakao** [comment]
I should clarify this. 
The size of the OCI image is not the problem here.
The way we download the image doesn't allow for real differential updates tho so a lot of the image needs to be downloaded on any update. 

So this is an issue with the download from ABRoot (or propably Prometheus) and not with Vib itself.
